spring:
  application:
    name: feign
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
#Feign默认启用ribbon开启负载均衡和重试
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
#对指定微服务进行负载均衡配置
item-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
#开启Hystrix降级熔断策略    
feign:
  hystrix:
    enabled: true
#减少降级超时时间  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
