spring:
  application:
    name: ribbon
    
server:
  port: 3001
  
eureka:
  client:
    service-url: 
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  
#hystrix超时时间  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
#acturator
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream